### ISSUE TITLE
Trezor wallet dependency issue causing error in `wallet-adapter-wallets`

### ISSUE THREAD

**Issue by mcintyre94** [anza-xyz/wallet-adapter#918]
**Describe the bug**

When importing from `wallet-adapter-wallets` there's an error caused by a bad dependency in `wallet-adapter-trezor`:

```sh
 ⨯ ./node_modules/@trezor/connect-web/lib/channels/serviceworker-window.js:4:19
Module not found: Can't resolve '@trezor/connect-common/src/messageChannel/abstract'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@trezor/connect-web/lib/popup/index.js
./node_modules/@trezor/connect-web/lib/index.js
./node_modules/@solana/wallet-adapter-trezor/lib/esm/adapter.js
./node_modules/@solana/wallet-adapter-trezor/lib/esm/index.js
./node_modules/@solana/wallet-adapter-wallets/lib/esm/index.js
./app/layout.tsx
```

Note that [@trezor/connect-web ](https://www.npmjs.com/package/@trezor/connect-web) and [@trezor/connect-common](https://www.npmjs.com/package/@trezor/connect-common) have had recent updates, and an app installing `wallet-adapter-wallets` has the latest version of each (9.2.0 and 0.0.29 respectively)

**To Reproduce**

- Stackblitz repro: https://stackblitz.com/edit/nextjs-5sgyn3?file=app%2Flayout.tsx
- `npm install && npx next dev`

**Expected behavior**

No error, Next app starts correctly

@gabrielKerekes tagging because you opened the previous Trezor PR - could you figure out how the adapter dependencies need to be set up please?

**Comment by mcintyre94** [comment]
> As a temporary solution for wallet-adapter we could pin @trezor/connect-web to version 9.1.6? What do you think?

Thanks for looking into this :) That sounds like a good workaround for now! Would get the Trevor adapter working for those who need it and fix the umbrella package for everyone. Would you be able to open a PR on the adapter for that?

**Comment by gabrielKerekes** [comment]
> Would you be able to open a PR on the adapter for that?

https://github.com/anza-xyz/wallet-adapter/pull/920

**Comment by yakphi** [comment]
> I opened an issue in Trezor Connect repo - [trezor/trezor-suite#11442](https://github.com/trezor/trezor-suite/issues/11442). Unfortunately I'm not able how to fix this myself as it seems to be an issue with Trezor Connect not the integration into wallet adapter.
> 
> As a temporary solution for wallet-adapter we could pin `@trezor/connect-web` to version `9.1.6`? What do you think?

This solve the build issue util the fix is released

For yarn adding the resolutions rule to package.json.

  "resolutions": {
    "@trezor/connect-web": "9.1.6"
  }

**Comment by gabrielKerekes** [comment]
A fixed @trezor/connect-web has been released yesterday. Available on [NPM](https://www.npmjs.com/package/@trezor/connect-web). I tested the reproduction repo ([here](https://stackblitz.com/edit/nextjs-5sgyn3?file=app%2Flayout.tsx)) and it now builds as expected 👍 I tested end to end with the `nextjs-starter` in this repo and that worked as well.

**Comment by mcintyre94** [comment]
Hmm I'm still seeing the error on the stackblitz repro, but overriding to `9.2.1` works correctly for me.

**Comment by gabrielKerekes** [comment]
> Hmm I'm still seeing the error on the stackblitz repro, but overriding to 9.2.1 works correctly for me.

The override shouldn't be needed. Maybe the issue is that version `9.2.0` was written in `package-lock.json`? Or some similar problem?

**Comment by mcintyre94** [comment]
Looks like something was cached, all good! Looks like this should be sorted for good :) Thanks again Gabriel!
